# Generated by Django 3.0.8 on 2021-03-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_courier_regions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='earning',
            new_name='earnings',
        ),
    ]
