# Generated by Django 3.0.8 on 2021-03-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_auto_20210328_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courier',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
