# Generated by Django 3.1.7 on 2021-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(default='Артем', max_length=128),
            preserve_default=False,
        ),
    ]
