# Generated by Django 3.0.8 on 2021-03-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0004_auto_20210328_1150'),
        ('orders', '0002_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='couriers.Courier'),
        ),
        migrations.DeleteModel(
            name='CompletedOrder',
        ),
    ]
