# Generated by Django 3.0.8 on 2021-03-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210328_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed_by',
            new_name='courier',
        ),
    ]
